# Generated by Django 3.1.2 on 2020-10-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_edit_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='re',
            old_name='name',
            new_name='mname',
        ),
    ]
